---
title: "Intermediate SQL"
author: "Carter Wolff"
date: "2023-09-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---Chapter 1: Selecting Data
-When using COUNT() or similar functions, the DISTINCT command must be included in the COUNT() parentheses, if you wish to count unique values in a field. 
  -Otherwise (when not using COUNT like functions, the DISTINCT can follow SELECT directly)
-SQL query execution
  -SQL code is not executed in the order that it is written. Most of the time, the first command that is executed is telling SQL what table to make the query request to (using the FROM command. Then you can start to specify chunks of data within that table using SELECT, LIMIT, etc...)
  -comma errors are common in SQL debugging. It is a type of error that sometimes does not provide a helpful error message, requiring a longer debugging process to resolve errors in code
-SQL style
  -New lines, capitilization, and indentation are all NOT required for SQL. However, it makes queries difficult to read. Thus, a standard style is usually used.
  -Style guides
    -Capitilization for commands in the Query request (i.e., SELECT, AS, FROM, COUNT, etc...)
    -New lines for each unique command
    -inclusion of a semi colon at the end of the query request. semi colon is not required in PostGreSQL, but is good practice for your code to be transferable
-Spaces in field names should not exist. However if they do, using " " to surround the field name wil tell SQL that it is a single field

---Chapter 2: Filtering Records
-Filtering numbers
  -WHERE is a command that allows you to specify a clause that must be met for the record to be selected. WHERE can be used with many operations, such as <, >, <=, >=
    -while = is an accepted operation for SQL, != and <> are operations to represent not equal. Most databases support both notations. A few only support <>
-WHERE also works with strings. To specify strings, use single quotation marks to surround the desired string
-For order of execution, WHERE comes before LIMIT, but after SELECT
-Filtering with multiple criteria
-Some commands to include multiple comparisons in a filtering land
  -OR: I.e., WHERE condition1 OR ccondition2
  -AND: I.e., WHERE condition1 AND condition2
  -BETWEEN: quick shorthand that replaces >=, <= functions: written as WHERE field name BETWEEN cond1 AND cond2
    -between is inclusive for the values specified in the BETWEEN statement
  -Parentheses can be used to include multiple filtering conditions with multiple operators. I.e., WHERE (cond1 OR cond2) AND (condA OR condB)
    -examples show below
```{sql connection=}
--AND--
-- Select all records for German-language films released after 2000 and before 2010
SELECT *
FROM films
WHERE language = 'German'
    AND (release_year > 2000 AND release_year < 2010); 

--OR--
-- Find the title and year of films from the 1990 or 1999
SELECT title, release_year
FROM films
WHERE (release_year = 1990 OR release_year = 1999)
-- Select only English and Spanish films
	AND (language = 'English' OR language = 'Spanish')
-- Filter films with more than $2,000,000 gross
	AND gross > 2000000;
	
--BETWEEN--
-- Select the title and release_year for films released between 1990 and 2000
SELECT title, release_year
FROM films
WHERE release_year BETWEEN 1990 AND 2000
-- Narrow down your query to films with budgets > $100 million
	AND budget > 100000000
-- Only include Spanish or French-language films
	AND (language = 'Spanish' OR language = 'French');
```
    
Filtering Text
-Text can be filtered top a higher degree than simply equal/not equal. Some keywords to help filter text are:
  -LIKE: searches for records in a field that meat the LIKE command
  -NOT LIKE: searches for records in the field that do not meet the NOT LIKE
  -IN: searches for records in the field that contain the text specified in the IN command
  ALL of these keywords can be used with WHERE. There are two wildcard characters, the % and the _ that specify how these keywords operate in SQL
    %: matches zero, one or many characters
      e.g., SELECT name FROM people WHERE name LIKE 'Ade%'
        -This will include any name with Ade
    _: matches a single character
      e.g., SELECT name FROM people where name Like 'Ev_'
        -This will only return names with three letters, such as Eve or Eva
  The position of the wildcard is important for evaluating the text in different postions
    -SELECT name FROM people WHERE name LIKE '%r';
      -this code will find all people whose name ends in 'r'
    -SELECT name FROM people WHERE name LIKE '__t%';
      -while this code will find all people whose name contains a t as the third character.
  -The IN keyword is useful as a shorthand for multiple OR conditions. The following two lines of code run the same.
    -SELECT title FROM films WHERE release_year IN (1920, 1930, 1940);
    -SELECT title FROM films WHERE release_year = 1920 OR release_year = 1930 OR release_year = 1940;
    
```{sql connection=}
-- Select the names that start with B
SELECT name
FROM people
WHERE name LIKE 'B%';

SELECT name
FROM people
-- Select the names that have r as the second letter
WHERE name LIKE '_r%';

SELECT name
FROM people
-- Select names that don't start with A
WHERE name NOT LIKE 'A%';

-- Find the title and release_year for all films over two hours in length released in 1990 or 2000
SELECT title, release_year
FROM films
WHERE duration > 120
AND release_year IN (1990, 2000);

-- Find the title and language of all films in English, Spanish, and French
SELECT title, language
FROM films
WHERE language IN ('English', 'Spanish', 'French');

-- Find the title, certification, and language all films certified NC-17 or R that are in English, Italian, or Greek
SELECT title, certification, language
FROM films
WHERE certification IN ('NC-17', 'R')
AND language IN ('English', 'Italian', 'Greek');

--More complex query--
-- Count the unique titles
SELECT COUNT(DISTINCT TITLE) AS nineties_english_films_for_teens
FROM films
-- Filter to release_years to between 1990 and 1999
WHERE release_year BETWEEN 1990 AND 1999
-- Filter to English-language films
	AND language = 'English'
-- Narrow it down to G, PG, and PG-13 certifications
	AND certification IN ('G', 'PG', 'PG-13');
```

-Filtering NULL values in SQL
  -null values are represented in SQL as null
  -IS NULL can be combined with the WHERE clause to filter records for only those that contain null for the specified field
    -Similarly IS NOT NULL filters for records that are not null
    -Both IS NULL and IS NOT NULL can be combined with the COUNT command in SELECT to tally the amount of null or non null values respectively
```{sql connection=}
-- List all film titles with missing budgets
SELECT title AS no_budget_info
FROM films
WHERE budget IS NULL;

-- Count the number of films we have language data for
SELECT COUNT(*) as count_language_known
FROM films
WHERE language IS NOT NULL;
```

---Chapter 3: Aggregate Functions
-Summarizing data
  -Descriptive statistics used to condense data. COUNT is one such keyword that we have seen so far. All of these keywords follow the SELECT keyword. I.e.,
    -SELECT MAX(budget) or SELECT AVG(budget)
  -Common summarizing keywords
    -COUNT()
    -SUM(): numerical fields only
    -MIN()
    -MAX()
    -AVG(): numerical fields only
    -when using count, min, and max with non numerical fields, the keywords will select the data based on the field type. That is, if it is a string, min and max will
    select the first and last string based on alphabetical order
    -ROUND(): contains two parameters -> The number to round and the decimal place to round it to. Omitting the second parameter defaults to 0 decimal places
      -passing negative numbers as the second parameter will round left of the decimal 
    
-Summarizing Subsets,
  -This combines the WHERE clause with the summarizing keywords specified above
  
```{sql connection=}
-- Query the sum of film durations
SELECT SUM(duration) AS total_duration
FROM films;

-- Calculate the average duration of all films
SELECT AVG(duration) AS average_duration
FROM films;

-- Calculate the average duration of all films
SELECT AVG(duration) AS average_duration
FROM films;

-- Find the duration of the shortest film
SELECT MIN(duration) AS shortest_film
FROM films

--Summarizing Subsets and Rounding--
-- Calculate the sum of gross from the year 2000 or later
SELECT SUM(gross) as total_gross
FROM films
WHERE release_year >= 2000;

-- Calculate the average gross of films that start with A
SELECT AVG(gross) as avg_gross_A
FROM films
WHERE title LIKE 'A%';

-- Calculate the lowest gross film in 1994
SELECT MIN(gross) AS lowest_gross
FROM films
WHERE release_year = 1994;

-- Calculate the highest gross film released between 2000-2012
SELECT MAX(gross) AS highest_gross
FROM films
WHERE release_year BETWEEN 2000 AND 2012

-- Round the average number of facebook_likes to one decimal place
SELECT ROUND(AVG(facebook_likes), 1) AS avg_facebook_likes
FROM reviews;

-- Calculate the average budget rounded to the thousands
SELECT ROUND(AVG(budget), -3) AS avg_budget_thousands
FROM films;
```

Arithmetic
-SQL assumes that if you enter an integer into the command line, you should get an integer out
  -thus, SELECT (4/3) would give an output of 1
  -to correct this, you need to specify the decimal, so that SQL knows to reurn the numeric value with decimals
  
  
---Chapter 4: Sorting and Grouping
-The ORDER BY keyword can sort by the specified field. By default, it is set to sort in Ascending order
  -You can also specify to sort in Ascending order by using ASC following the field you list in the ORDER BY statement. 
    -This also allows you to sort in Descending order using DESC.
    ORDER BY release_year ASC or ORDER BY release year DESC sort in ascending and descending order respectively
  -To sort by multiple fields, list all fields followed by a comma
    -i.e., ORDER BY field1 DESC, field2 DESC, field 3 ASC etc...

```{sql connection=}
-- Select name from people and sort alphabetically
SELECT name
FROM people
ORDER BY name;

-- Select the title and duration from longest to shortest film -- including null values
SELECT title, duration
FROM films
ORDER BY duration DESC;

-- Select the release year, duration, and title sorted by release year and duration in that order
SELECT release_year, duration, title
FROM films
ORDER BY release_year, duration;

-- Select the certification, release year, and title sorted by certification and release year (with certification in alphabetical and newest films first)
SELECT certification, release_year, title
FROM films
ORDER BY certification, release_year DESC;
```

-Grouping Data
  -grouping allows you to make calculations on subsets of data. 
  -Grouping uses the GROUP BY keyword
    -similar to dplyr in R, GROUP BY will pass the given fields and coalesce them into groups by the specified field
  -GROUP BY can be used in tandem with summary keywords and ORDER BY.
    -therefore, one can group and calculate a given summary statistic. After which they can order the groups within the listed GROUP BY field

```{sql connection=}
-- Find the release_year and film_count of each year (i.e., find the number if films released each year)
SELECT release_year, COUNT(*) AS film_count
FROM films
GROUP BY release_year;

-- Find the release_year and average duration of films for each year
SELECT release_year, AVG(duration) as avg_duration
FROM films
GROUP BY release_year;

-- Find the release_year, country, and max_budget, then group and order by release_year and country
SELECT release_year, country, MAX(budget) AS max_budget
FROM films
GROUP BY release_year, country
ORDER BY release_year, country;

-- Find the year that had the most unique languages in films
SELECT release_year, COUNT(DISTINCT language)
FROM films
GROUP BY release_year
ORDER BY count DESC;

```

-Filtering groupd data
  -Groups contain their own keyword, HAVING
    -Having applies specifically to groups due to the order of execution that SQL operates by. Since WHERE exectutes before GROUP BY, it cannot be used to filter
      -Thus HAVING filters groups while WHERE filters individual records

```{sql connection=}
-- Select the country and distinct count of certification as certification_count
SELECT country, COUNT(DISTINCT certification) AS certification_count
FROM films
-- Group by country
GROUP BY country
-- Filter results to countries with more than 10 different certifications
HAVING COUNT(DISTINCT certification) > 10;


-- Select the country and average_budget from films
SELECT country, ROUND(AVG(budget), 2) AS average_budget
FROM films
-- Group by country
GROUP BY country
-- Filter to countries with an average_budget of more than one billion
HAVING AVG(budget) > 1000000000
-- Order by descending order of the aggregated budget -- remember that since ORDER BY is executed after SELECT, the alias is specified, not the original field name
ORDER BY average_budget DESC

--putting all the keywords together--
-- Select the release_year for films released after 1990, grouped by year. Also select the average budget and average gross of these films
SELECT release_year, AVG(budget) AS avg_budget, AVG(gross) AS avg_gross
FROM films
WHERE release_year > 1990
GROUP BY release_year
-- Modify the query to see only years with an avg_budget of more than 60 million
HAVING AVG(budget) > 60000000
-- Order the results from highest to lowest average gross and limit to one
ORDER BY avg_gross DESC
LIMIT 1;
```
